# Generated by Django 3.0.5 on 2020-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.SlugField()),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('AU', 'Authenticated User'), ('MD', 'Moderator'), ('AD', 'Administrator'), ('AJ', 'Administrator Django')], default='AU', max_length=2)),
            ],
        ),
    ]
