# Generated by Django 3.0.5 on 2020-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AU', 'user'), ('MD', 'moderator'), ('AD', 'administrator')], default='AU', max_length=2),
        ),
    ]
