# Generated by Django 3.0.5 on 2020-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200611_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('MD', 'moderator'), ('AD', 'admin')], default=1, max_length=2),
        ),
    ]
