# Generated by Django 3.0.5 on 2020-06-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200612_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
