# Generated by Django 2.2.9 on 2020-06-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_categories_comments_genres_genretitles_review_titles"),
    ]

    operations = [
        migrations.RemoveField(model_name="comments", name="review",),
        migrations.AddField(
            model_name="comments",
            name="review_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_id",
                to="api.Review",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="titles",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Genres",
            ),
        ),
        migrations.AlterField(
            model_name="review", name="text", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="titles",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="api.Categories",
            ),
        ),
        migrations.AlterField(
            model_name="titles", name="year", field=models.IntegerField(),
        ),
        migrations.DeleteModel(name="GenreTitles",),
    ]
