# Generated by Django 2.2.9 on 2020-06-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20200619_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titles",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Categories",
            ),
        ),
    ]
