# Generated by Django 3.0.5 on 2020-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200628_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
