# Generated by Django 3.0.5 on 2020-09-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
