# Generated by Django 3.0.5 on 2020-09-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
