# Generated by Django 3.0.5 on 2020-09-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
